### ISSUE TITLE
What's the difference between this project and edl?

### ISSUE THREAD

**Issue by yingfeng** [baidu/paddle-on-k8s-operator#2]
[edl](https://github.com/PaddlePaddle/edl) is also the paddle operator on k8s, working together with the [cloud](https://github.com/PaddlePaddle/cloud) project, what's the difference between these two projects?

**Comment by tizhou86** [comment]
Hi @yingfeng, this project is mainly focusing on the operator side, how to handle pserver model state machine, how to attach persistent storage with data shuffling, and how to co-schedule the pod in the single job, those are more likely to be resolved in a new underlay project.

**Comment by yingfeng** [comment]
so it means the [edl](https://github.com/PaddlePaddle/edl) will be abandoned, while this k8s operator, together with the new underlay project will be used to replace  [edl](https://github.com/PaddlePaddle/edl) in future?

**Comment by tizhou86** [comment]
EDL is used in Baidu as the core of the machine learning platform and it's already in stable version, this project will be used in Baidu public cloud's deep learning solution, cooperate with Baidu cloud provider,  to provide enterprise users better deep learning experiences.

**Comment by yingfeng** [comment]
got it,thanks~
